baseURL = "https://www.france-formosa.org/"
languageCode = "fr-FR"
title = "France Formosa"
defaultContentLanguage = "fr"
enableRobotsTXT = true

[params]
  description = "Dédié aux relations franco-taïwanaises"
  author = "France Formosa"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Notre mission"
    url = "/mission/"
    weight = 2
  [[menu.main]]
    name = "Nos axes"
    url = "/axes/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
